# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=75)),
                ('event_theme', models.CharField(blank=True, max_length=75)),
                ('min_grade', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True)),
                ('max_grade', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True)),
                ('time_zone', models.CharField(blank=True, help_text=b'ex: PST', max_length=15)),
                ('start_time', models.DateTimeField(blank=True, help_text=b'Please use 24 hour time.', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text=b'Please use 24 hour time.', null=True)),
                ('location_name', models.CharField(blank=True, help_text=b'ex: Pleasanton Library', max_length=75)),
                ('location_address_1', models.CharField(blank=True, help_text=b'ex: 400 Old Bernal Ave', max_length=75)),
                ('location_address_2', models.CharField(blank=True, help_text=b'ex: Building 2, Lobby, etc.', max_length=75)),
                ('city', models.CharField(blank=True, help_text=b'ex: Pleasanton', max_length=75)),
                ('state', models.CharField(blank=True, help_text=b'ex: CA', max_length=2)),
                ('zip_code', models.CharField(blank=True, help_text=b'ex: 94566', max_length=5)),
                ('country', models.CharField(blank=True, help_text=b'ex: United States', max_length=75)),
                ('event_details', models.TextField(blank=True, default=None, help_text=b'Detailed description of your event goes here.')),
                ('optional_event_details', models.TextField(blank=True, default=None, help_text=b'Additional detailed description of your event goes here.')),
                ('event_FAQ', models.TextField(blank=True, default=None, help_text=b'FAQs go here.')),
                ('event_contact_name', models.CharField(blank=True, help_text=b'Name of the contact for your event.', max_length=30)),
                ('event_contact_phone', models.CharField(blank=True, help_text=b'Phone number of the contact for your event.', max_length=30)),
                ('event_contact_email', models.CharField(blank=True, help_text=b'Email of the contact for your event.', max_length=255)),
                ('event_banner', models.FileField(blank=True, help_text=b'Dimensions: minimum 2160 x 1080px. File Type: JPEG, PNG, BMP, or GIF. File Size: no larger than 10 MB.', null=True, upload_to=b'images/')),
                ('event_access_code', models.CharField(help_text=b'clarify: 10 or fewer character access code for your event.', max_length=10)),
                ('registration_code', models.CharField(help_text=b'clarify: 10 or fewer character access code for your event.', max_length=10)),
            ],
        ),
    ]
